# Generated by Django 3.0.4 on 2020-03-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pullupclub', '0003_auto_20200328_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('type', models.CharField(choices=[('BD', 'By Distance'), ('BC', 'By Count')], max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='pullupsession',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
